### ISSUE TITLE
Qual o tipo de licença?

### ISSUE THREAD

**Issue by duilioelias** [redeecologica/pedidos#11]
Olá Galera,

Gostaria de saber o tipo de licença para saber o que posso ou não fazer com o código de vocês.

Desde já agradeço

**Comment by rodrigoprimo** [comment]
Eu tenho a impressão de que o processo para adicionar uma licença é um pouco mais complexo do que só adicionar o texto ao README do projeto:

https://www.gnu.org/licenses/gpl-howto.html

Se não me engano precisa inclusive adicionar um cabeçalho em todos os arquivos (não tenho certeza disso). Se tiver mesmo, deve ter algum esquema pronto para fazer isso automaticamente.

**Comment by alinealfa** [comment]
Adicionei no raiz o arquivo LICENSE.txt com o conteúdo da GPL para ficar mais padronizado com os demais projetos no github ( https://help.github.com/articles/open-source-licensing/ ) e editei no README a menção à licença.

Sobre adicionar menção em cada arquivo fonte do projeto: existe muita discussão na internet sobre esta obrigatoriedade. Depois de ler algumas opiniões, e _for the sake of simplicity_, vou manter menção apenas no README; pela natureza do projeto, acho pouco provável que um arquivo solto seja distribuído, de modo que fique "perdido" e a pessoa que o esteja reutilizando fique sem saber qual a origem e licença associada.

**Comment by rodrigoprimo** [comment]
Perfeito!

**Comment by rodrigoprimo** [comment]
Obrigado @duilioelias por chamar nossa atenção em relação a isso :)

**Comment by alinealfa** [comment]
o github identifica a presença do arquivo de licença e classifica automaticamente:
![image](https://cloud.githubusercontent.com/assets/4013036/19041904/62f65142-8960-11e6-9f5d-aef33d2f0b58.png)
