### ISSUE TITLE
Otimizar a versão para impressão do pedido do cestante

### ISSUE THREAD

**Issue by alinealfa** [redeecologica/pedidos#9]
Sugestão da Bibi Cintrão (núcleo Santa Teresa):
Melhoria para que a versão para impressão do pedido do cestante não exiba o menu do sistema e outros componentes, de modo que otimize a impressão (economia de recursos).

**Comment by alinealfa** [comment]
Atendido pelo commit 07bf380

**Comment by rodrigoprimo** [comment]
@alinealfa se quiser é possível associar um commit a uma issue diretamente pela mensagem de commit. Se achar mais fácil, sugiro usar. Veja a seção "References" no link abaixo:

https://guides.github.com/features/issues/
